language: php

php:
  - 5.5
  - 5.4
  - 5.3
  
sudo: false

git:
  submodules: true

script:
  - ls -liah
  - phpunit --color UTRSBot.php

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-utrs-dev"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"